### ISSUE TITLE
SteamTinkerLaunch on Linux

### ISSUE THREAD

**Issue by Dillacorn** [valignatev/socd#30]
Hey I just wanted to let you know it's possible to install AutoHotkey with SteamTinkerLauncher and run it with "use custom command" and "Fork custom command" checked + "socd.ahk" for allowing socd cleaning on WASD keys.

I got a working .ahk script for a & d keys

```
#InstallKeybdhook
#UseHook On
#MaxHotkeysPerInterval 200

;; * Pressing both Left & Right buttons cancels each other.
;; ?  Left: a
;; ? Right: d

~a::
    if(GetKeyState("d", "p"))
        SendInput {d up}{f up}
Return

~d::
    if(GetKeyState("a", "p"))
        SendInput {a up}{f up}
Return

~a up::
    if(GetKeyState("d", "p"))
        SendInput {d down}
Return

~d up::
    if(GetKeyState("a", "p"))
        SendInput {a down}
Return

;; ! BSDK
```

Does your socd app rely on any dependencies I need to install with winetricks? Reason why it can't grab config file when I try to launch it in the same manor? Same issue with "SnapKey" by "cafali" here on github.

I also tried socd application forked for Linux by "it0946" but I think it may only work with native Linux applications?...not sure I've only been testing in a vm so far so that might be my issue.

Please look into this! I'd much rather run your script with Wine/Proton games than AutoHotkey... Worried about anti-cheats primarily.

**Comment by valignatev** [comment]
Hey! socd doesn't use any 3rd party dependencies apart from pure win32 calls and some libc (for opening and reading config files). It might not be able to grab the config file if wine fucks with current working directories, because exe only looks for the config file right next to it. Forked project for linux should theoretically work with wine as well, because it works directly on the input device, but there are a couple caveats:
1) It needs to be run under sudo
2) it creates a new virtual keyboard that it then sends inputs to, and if a particular game listens to one of existing keyboards instead then it won't see inputs from a new device. 

I'm currently rewriting my program to also support Linux natively, and hopefully I'll handle that.

**Comment by Dillacorn** [comment]
https://github.com/cafali/SnapKey/issues/4#issuecomment-2251568839

I found a solution using SnapKey.

Your app may also work with steamtinkerlaunch but I have not tested it in the same manor.
